# Numpy
<a href="https://colab.research.google.com/github/milocortes/diplomado_ciencia_datos_mide/blob/edicion-2024/talleres/numpy_mide_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


![numpy-2.png](attachment:numpy-2.png)
source : https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html


# ¿CONOCEN LAS OPERACIONES VECTORIZADAS?

# Numpy

**Numpy** es una biblioteca especializada en cálculos numéricos.

Numpy es la base de muchas bibliotecas de alto nivel para ciencia de datos y aprendizaje de máquina (Pandas, scikit-learn, TensorFlow, Pytorch, etc.).

La estructura básica de Numpy son los **numpy arrays**.

Las arreglos de Numpy son similares a la lista de Python pero con algunas ventajas adicionales:

* Los Numpy arrays utilizan una cantidad de memoria más pequeña y son más rápidos en la mayoría de los casos.
* Los Numpy arrays son más convenientes cuando se accede a más de dos ejes, conocidos como datos *multidimensionales* (las listas multidimensionales son difíciles de acceder y modificar).
* Los Numpy arrays tienen una funcionalidad de acceso más poderosa, como es el caso del bradcasting.
* **Numpy almacena datos en fragmentos (chunks) contiguos de memoria y admite operaciones vectorizadas en sus datos.**

In [1]:
[[1,2,3], [2,3,5]]

[[1, 2, 3], [2, 3, 5]]

# Dependencias de Numpy

![numpy_dependencies.jpeg](attachment:numpy_dependencies.jpeg)

In [4]:
import numpy as np
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    versio

# Memoria principal y cachés

La **memoria** es en realidad una jerarquía de componentes que almacenan datos, que van desde uno o más niveles de **cachés** pequeños y rápidos hasta una **memoria principal** grande y relativamente lenta:


Principio arquitectónico: **los procesadores y la memoria principal están muy separados**.


Uno de los retos es tratar de reducir el tiempo (latencia) que lleva acceder a la
memoria.

# Procesadores

Un multiprocesador consta de múltiples **procesadores** de hardware, cada uno de los cuales ejecuta un programa secuencial.

En arquitecturas multiprocesador o de un solo procesador, la unidad básica de tiempo es el **ciclo**: el tiempo que tarda un procesador en buscar y ejecutar una sola instrucción...


para buscar? ¿dónde? en la memoria principal.



# Memoria principal y cachés

Los procesadores comparten una memoria principal, que es un arreglo de **palabras** indizadas por una **dirección**.

El tamaño de una palabra o una dirección depende de la plataforma, pero normalmente es de 32 o 64 bits.

![memoria-principal.jpg](attachment:memoria-principal.jpg)


Un procesador lee un valor de la memoria enviando un mensaje que contiene la dirección deseada a la memoria.

![lee-valor.jpg](attachment:lee-valor.jpg)


El mensaje de respuesta contiene los **datos** asociados, es decir, el contenido de la memoria en esa dirección.

![regresa-valor.jpg](attachment:regresa-valor.jpg)

Un procesador escribe un valor enviando la dirección y los nuevos datos a la memoria, y la memoria envía un reconocimiento cuando se han instalado los nuevos datos.

![escribe-valor.jpg](attachment:escribe-valor.jpg)

Recuerda:


Principio arquitectónico: **los procesadores y la memoria principal están muy separados**.

Un acceso a la memoria principal puede tomar cientos de ciclos, por lo que existe un peligro real que un procesador pase gran parte de su tiempo esperando que la memoria responda a las solicitudes.

Los sistemas modernos alivian este problema al introducir uno o más *cachés*: pequeñas memorias que están situadas más cerca de los procesadores y, por lo tanto, son mucho más rápidas que la memoria principal.

Estos cachés están situados lógicamente "entre" el procesador y la memoria: cuando un procesador intenta leer un valor de una dirección de memoria determinada, primero busca si el valor ya está en el caché y, de ser así, no necesita para realizar el acceso (más lento) a la memoria.

### Cachés *L1*, *L2* y *L3*

Si el valor deseado se encuentra en el caché, se dice que el procesador logra un **hit** de caché y, de lo contrario, logra un **miss** de caché.

En la práctica, la mayoría de los procesadores tienen dos o tres niveles de cachés, llamados cachés *L1*, *L2* y *L3*. Todo los cachés, a excepción del último (el más grande), normalmente residen en el mismo chip que el procesador.

![cache_levels.png](attachment:cache_levels.png)

# Granularidad

Si un procesador lee o escribe una ubicación de memoria, también es probable que lea o escriba ubicaciones *cercanas* .

Para aprovechar esto, los cachés suelen operar con una **granularidad** mayor que una sola palabra: un caché contiene un grupo de palabras vecinas llamadas **líneas de caché**.


# Operaciones vectorizadas

Los procesadores tienen unidades vectoriales especiales que pueden cargar y operar en más de un elemento de datos a la vez.

**Vectorización** es el proceso de agrupar operaciones para que se pueda realizar más de una a la vez.
![vectorized_operation.png](attachment:vectorized_operation.png)

# mucha teoría por ahora...  manos a la obra

In [10]:
import numpy as np

a = np.array([2,3,4,5])
a.ndim

1

In [11]:
# Creación de un arreglo 2D a partir de una lista de listas
b = np.array([[1,2],
              [3,4]])
b.ndim

2

In [17]:
# Creación de un arreglo 2D a partir de una lista de listas
d = np.array([[12,23],
              [35,44]])
b

array([[1, 2],
       [3, 4]])

In [18]:
# Creación de un arreglo 3D a partir de una lista de listas de listas
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
a.shape

(4,)

In [29]:
t = np.array(
    [[1,2],
     [3,4]]
)
t

array([[1, 2],
       [3, 4]])

In [25]:
b.shape

(2, 2)

array([[[ 1,  4],
        [ 9, 16]],

       [[ 5, 12],
        [21, 32]]])

Se pueden realizar operaciones aritméticas con los operadores <code>+</code>, <code>-</code>, <code>*</code>, <code>/</code> en numpy arrays.

Estas *element-wise operations* combinan dos matrices <code>a</code> y <code>b</code> (por ejemplo, sumándolas con el operador <code>+</code>) combinando cada elemento del arreglo <code>a</code> con el elemento correspondiente del arreglo <code>b</code>.

In [33]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [2, 0, 0]])
b = np.array([[1, 1, 1],
              [1, 1, 2],
              [1, 1, 2]])

a - b

array([[ 0, -1, -1],
       [ 0,  0, -1],
       [ 1, -1, -2]])

array([[ 0, -1, -1],
       [ 0,  0, -1],
       [ 1, -1, -2]])

array([[1, 0, 0],
       [1, 1, 2],
       [2, 0, 0]])

array([[1. , 0. , 0. ],
       [1. , 1. , 0.5],
       [2. , 0. , 0. ]])

Numpy proporciona muchas más capacidades para manipular arreglos, como <code>np.max()</code>, <code>np.min()</code>, <code>np.average()</code > funciones que calculan los valores *máximo*,*mínimo* y *promedio* de todos los valores en un arreglo de numpy,respectivamente.

In [38]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [2, 0, 0]])

np.max(a, axis= 0)

array([2, 1, 1])

In [39]:
np.min(a, axis= 0)

array([1, 0, 0])

In [41]:
np.average(a)

0.6666666666666666

# Problema 1

Abordemos este problema utilizando los datos salariales de Alice, Bob y Tim.

Parece que Bob tiene del salario más alto de los últimos tres años.

Pero, ¿realmente tiene un mayor ingreso considerando la tasa de impuestos individuales respectiva a cada individuo?

In [42]:
## Data : yearly, salary in ($1000) [2017, 2018, 2019]
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]

salaries = np.array([alice,bob,tim])
taxation = np.array([[0.2, 0.25, 0.22],[0.4,0.5,0.5],[0.1,0.2,0.1]])

# La multiplicación elemento por elemento de dos arreglos multidimensionales es denominado el producto Hadamard


In [49]:
np.max(salaries - salaries*taxation)

81.0

In [50]:
salaries - salaries*taxation

array([[79.2 , 75.75, 80.34],
       [66.  , 54.  , 52.5 ],
       [81.  , 70.4 , 76.5 ]])

# Slicing, Broadcasting y tipos de arreglos

La indización y segmentación en numpy son similares a la indización y segmentación en Python: se accede a los elementos de una arreglo unidimensional mediante la operación de paréntesis <code>[]</code> para especificar el índice o el rango del índice.

También se puede usar la indización para un arreglo multidimensional especificando el índice para cada dimensión de forma independiente y usando índices separados por comas para acceder a las diferentes dimensiones.

Por ejemplo, la operación de indexación <code>y[0,1,2]</code> accedería al primer elemento del primer eje, al segundo elemento del segundo eje y al tercer elemento del tercer eje.

In [56]:
y = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[6, 7, 8], [8, 9, 10]]
])

y[1,1,2]

10

Los siguientes son ejemplos de segmentación en numpy:

In [58]:
a = np.array([55, 56, 57, 58, 59, 60, 61])
a[2:]

array([57, 58, 59, 60, 61])

In [61]:
a[:4:2]

array([55, 57])

In [ ]:
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

# obtiene la tercera columna


In [ ]:
# obtiene la segunda fila


In [ ]:
# obtiene  la segunda fila por cada 2 pasos


In [ ]:
# obtiene todas las columnas a excepción de la última


## Broadcasting

*Broadcasting* describe el proceso automático de poner dos matrices numpy en la misma forma para que pueda aplicar ciertas *element-wise operations*.


En el siguiente ejemplo, cada arreglo consta de varios *ejes*, uno para cada dimensión.

El atributo del arreglo <code>ndim</code> almacena el número de ejes de ese arreglo en particular

In [74]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [73]:
a = np.array([[1, 2, 3],
              [1, 2, 3],
              [1, 2, 3]])
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [75]:
b = np.array([[2, 1, 2] , [3, 2, 3], [4, 3, 4]])
b * a

array([[ 2,  2,  6],
       [ 3,  4,  9],
       [ 4,  6, 12]])

In [64]:
c = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]],
              [[1, 2, 4],[2, 3, 5],[3, 4, 6]]])
c.ndim

3

Cada arreglo tiene asociado un atributo <code>shape</code>, una tupla que da el número de elementos en cada eje.

Para un arreglo bidimensional, hay dos valores en la tupla: el número de filas y el número de columnas.

Para arreglos de mayor dimensión, la el elemento $\textit{i}$-ésimo de la tupla  especifica el número de elementos del $\textit{i}$-ésimo eje .

In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([[2, 1, 2] , [3, 3, 3], [4, 3, 4]])
b.shape

(3, 3)

In [ ]:
c.shape

(2, 3, 3)

Con la idea de <code>shape</code>, será más fácil comprender la idea general del broadcasting: llevar dos arreglos a la misma forma reorganizando los datos.

El broadcasting ajusta las operaciones de elementos de arreglos de numpy con diferentes formas.  

Por ejemplo, el operador de multiplicación <code>*</code> generalmente realiza la multiplicación por elementos cuando se aplica a arreglos de numpy.


Pero, ¿qué sucede si los datos de la izquierda y la derecha no coinciden? (Por ejemplo, ¿el operador de la izquierda es una matriz numérica, mientras que el de la derecha es un valor flotante?).

En este caso, numpy crea automáticamente un nuevo arreglo a partir de los datos del lado derecho. El nuevo arreglo  tiene el mismo tamaño y dimensionalidad que el arreglo de la izquierda y contiene los mismos valores.

Broadcasting, por lo tanto, es el acto de convertir un arreglo de baja dimensión en un arreglo de alta dimensión para realizar operaciones por elementos.

## Problema 2

Tienes datos para una variedad de profesiones y deseas aumentar los salarios de los científicos de datos en un 10 por ciento cada dos años.

In [91]:
import numpy as np

## Data: yearly salary in ($1000) [2025,2026,2027]
dataScientist = [130, 132, 137]
productManager = [127, 140, 145]
designer = [118, 118, 127]
softwareEngineer = [129, 131, 137]

employees = np.array([dataScientist,
                      productManager,
                      designer,
                      softwareEngineer])
employees = employees.astype(float)
employees[0,::2] = employees[0,::2] *1.1
employees

array([[143. , 132. , 150.7],
       [127. , 140. , 145. ],
       [118. , 118. , 127. ],
       [129. , 131. , 137. ]])

### Tipos de arreglos

Es posible que se haya dado cuenta de que el tipo de datos resultante no es flotante sino entero, incluso si está realizando aritmética de punto flotante.

Cuando se crea la matriz, numpy se da cuenta de que contiene solo valores enteros, por lo que asume que es un arreglo de enteros.

Cualquier operación que se realice en el arreglo de enteros no cambiará el tipo de datos y numpy redondeará a valores enteros.

Se puede acceder al tipo de arreglo usando la propiedad <code>dtype</code>

In [ ]:
employees.dtype

dtype('float64')

In [ ]:
dataScientist = [130, 132, 137]
productManager = [127, 140, 145]
designer = [118, 118, 127]
softwareEngineer = [129, 131, 137]

employees = np.array([dataScientist,
                      productManager,
                      designer,
                      softwareEngineer])

employees = employees.astype('float64')

employees[0,::] = employees[0,::] * 1.1
employees


array([[143. , 145.2, 150.7],
       [127. , 140. , 145. ],
       [118. , 118. , 127. ],
       [129. , 131. , 137. ]])

## Búsqueda, filtrado y broadcasting condicional de arreglos para detectar valores atípicos

El Índice de calidad del aire (AQI) mide el peligro de efectos adversos para la salud y se usa comúnmente para comparar las diferencias en la calidad del aire de las ciudades. En este ejercicio, observará el AQI de cuatro ciudades: Hong Kong, New York, Berlín y Montreal.

La solución encuentra ciudades contaminadas por encima del promedio, definidas como ciudades que tienen un AQI que está por encima del promedio general entre todas las mediciones de todas las ciudades.

Una tarea importante en estos casos es encontrar elementos en un arreglo  que cumplan con una determinada condición.

Exploremos cómo encontrar elementos de matriz que cumplan una condición específica.

Numpy ofrece la función <code>nonzero()</code> que encuentra los índices de los elementos en un arreglo que son distintos de cero.

In [ ]:
X = np.array([[1, 0, 0],
              [0, 2, 2],
              [3, 0, 0]])
np.nonzero(X)

(array([0, 1, 1, 2]), array([0, 1, 2, 0]))

El resultado es una tupla de dos arreglos de numpy. El pŕimer arreglo da los índices de fila y el segundo arreglo da los índices de columna de los elementos distintos de cero.

Podemos encontrar elementos que cumplan una determinada condición en un arreglo con operaciones booleanas de arreglos con broadcasting.

In [ ]:
X = np.array([[1, 0, 0],
              [0, 2, 2],
              [3, 0, 0]])
X == 2

array([[False, False, False],
       [False,  True,  True],
       [False, False, False]])

### Solución

In [ ]:
## Data: air quality index AQI data (row = city)
X = np.array(
            [[42, 40, 41, 43, 44, 43], # Hong Kong
             [30, 31, 29, 29, 29, 30], # New York
             [8, 13, 31, 11, 11, 9],   # Berlin
             [11, 11, 12, 13, 11, 12]] # Montreal
            )
cities = np.array(["Hong Kong", "New York", "Berlin", "Montreal"])



 ## Reshaping y Resizing

Cuando se trabaja con datos en forma de arreglos, suele ser útil reorganizar los arreglos y modificar la forma en que se interpretan.

Por ejemplo, una matriz $N\times N$ podría reorganizarse en un vector de tamaño $N^2$, o un conjunto de arreglos unidimensionales se podrían concatenar o apilar uno al lado del otro para formar una matriz.

NumPy proporciona un rico conjunto de funciones para este tipo de manipulaciones.


![reshape_numpy.png](attachment:reshape_numpy.png)

![resize_numpy.png](attachment:resize_numpy.png)

Hacer un reshape de un arreglo no requiere modificar los datos del arreglo subyacente; sólo
se realizan cambios en la forma en que se interpretan los datos, al redefinir el atributo <code>strides</code> del arreglo.

Un ejemplo de este tipo de operación es un arreglo 2D que se reinterpreta como un arreglo 1D (vector).

En NumPy, la función <code>np.reshape</code>, o el método de clase <code>ndarray</code> <code>reshape</code>, se pueden usar para reconfigurar cómo se interpretan los datos subyacentes.

La función <code>np.reshape</code> toma como argumentos un arreglo y la nueva forma de este:

In [ ]:
data = np.array([[1, 2], [3, 4]])


array([[1, 2, 3, 4]])

array([1, 2, 3, 4])

Es necesario que la nueva forma solicitada de la matriz coincida con el número de elementos en el tamaño original.

El reshape a un arreglo produce una vista del arreglo, y si se necesita una copia independiente de este, la vista debe copiarse explícitamente (por ejemplo, usando <code>np.copy</code>).


El método <code>np.ravel</code> (y su correspondiente método  del objeto <code>ndarray</code>) es un caso especial de reshape que colapsa todas las dimensiones del arreglo y devuelve un arreglo unidimensional *aplanado* (flattened) con una longitud que corresponde al número total de elementos del arreglo original.

El método <code>flatten</code> de un objeto  <code>ndarray</code>  realiza la misma función pero devuelve una copia en lugar de una vista.

In [ ]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

array([1, 2, 3, 4])

(4,)

Mientras que <code>np.ravel</code> y </code>np.flatten</code> colapsan los ejes de un arreglo en un arreglo unidimensional, también es posible introducir nuevos ejes en un arreglo, ya sea utilizando<code>np.reshape</code> o, al agregar nuevos ejes vacíos, utilizando la notación de indexación y la palabra clave <code>np.newaxis</code> en el lugar de un nuevo eje.

In [ ]:
data = np.arange(0, 5)


array([[0],
       [1],
       [2],
       [3],
       [4]])

array([[0, 1, 2, 3, 4]])

Además del reshaping y de la selección de subarreglos, con frecuencia es necesario fusionar arreglos en arreglos más grandes, por ejemplo, cuando se unen series de datos medidos o calculados por separado en un arreglo de mayor dimensión, como una matriz.

Para esta tarea, NumPy proporciona las funciones <code>np.vstack</code>, para apilar verticalmente, por ejemplo, filas en una matriz, y <code>np.hstack</code> para apilar horizontalmente, por ejemplo , columnas en una matriz.

Considere el siguiente caso: supongamos que tenemos arreglos de datos unidimensionales y queremos apilarlos verticalmente para obtener una matriz donde las filas están formadas por arreglos unidimensionales.

Podemos usar <code>np.vstack</code> para lograr esto

In [ ]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Si, en cambio, queremos apilar las matrices horizontalmente, para obtener una matriz donde los arreglos son los vectores columna, primero debemos hacer que los arreglos de entrada (<code>data</code>) sean arreglos bidimensionales de forma (1, 5 ) en lugar de arreglos unidimensionales de forma (5,).


Como se discutió anteriormente, podemos insertar un nuevo eje con <code>np.newaxis</code>:

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Operaciones con matrices y vectores

One of the main applications of the numpy arrays is to represent the mathematical concepts of vectors, matrices, and tensors, and in this use-case, we also frequently need to calculate vector and matrix operations such as scalar (inner) products, dot (matrix) products, and tensor (outer) products.

Una de las principales aplicaciones de los arreglos de numpy es representar los conceptos matemáticos de vectores, matrices y tensores, así como también realizar operaciones con vectores y matrices, como el producto escalar (internos),producto punto (matriz), producto tensorial (exterior), etc .

![numpy_matrix_operations.png](attachment:numpy_matrix_operations.png)


En numpy, el operador <code>*</code> se usa para la multiplicación por elementos. Para dos matrices bidimensionales A y B, la expresión A * B, por lo tanto, no calcula un producto matricial.


El operador <code>@</code> se utiliza para la multiplicación de matrices. También la función numpy <code>np.dot</code> se utiliza para este propósito.

To compute the product of two matrices $A$ and $B$, of size $N \times M$ and $M \times P$, which results in a
matrix of size $N \times P$, we can use:

Para calcular el producto de dos matrices $A$ y $B$, de tamaño $N \times M$ y $M \times P$, lo que da como resultado un matriz de tamaño $N \times P$, podemos usar:

In [ ]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
A @ B

array([[22, 28],
       [49, 64]])

In [ ]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])


Podemos calcular una matriz inversa de la siguiente manera:

In [ ]:
B = np.random.rand(3,3)
B

array([[0.94812002, 0.36921826, 0.75472651],
       [0.83308666, 0.30065259, 0.60104508],
       [0.76985114, 0.31240073, 0.80100831]])

In [ ]:
np.linalg.inv(B)

array([[-15.16487706,  17.14028385,   1.42726533],
       [ 58.47613306, -50.99659232, -16.8315815 ],
       [ -8.23123669,   3.41557734,   6.44115233]])

In [ ]:
np.linalg.inv(B) @ B

array([[ 1.00000000e+00, -7.96751619e-16, -5.90722841e-17],
       [-7.96184876e-16,  1.00000000e+00, -7.29295141e-16],
       [ 1.91365047e-16,  9.76905021e-19,  1.00000000e+00]])


Una expresión como $A^T = BAB^{-1}$, se puede calcular de la siguiente manera:

In [ ]:
A = np.random.rand(3,3)

In [ ]:
B @ A @ np.linalg.inv(B)

array([[-5.65635249,  6.30537871,  1.83356312],
       [-4.90133851,  5.5418111 ,  1.47935199],
       [-5.54363908,  5.94633464,  1.89380072]])


La función <code>np.dot</code> también se puede utilizar para la multiplicación de matriz-vector. $A^T = BAB^{-1}$ se calculará como:

In [ ]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

array([[-5.65635249,  6.30537871,  1.83356312],
       [-4.90133851,  5.5418111 ,  1.47935199],
       [-5.54363908,  5.94633464,  1.89380072]])

Numpy proporciona una estructura de datos alternativa al arreglo denominada <code>matrix</code>, para la cual expresiones como <code>A * B</code>  se implementan como multiplicación de matrices.

También proporciona algunos atributos especiales convenientes, como <code>matrix.I</code> para la matriz inversa.


Usando instancias de esta clase <code>matriz</code>, podemos escribir expresiones más legibles:

In [ ]:
A = np.matrix(A)
B = np.matrix(B)
Ap = B * A * B.I
Ap

matrix([[-5.65635249,  6.30537871,  1.83356312],
        [-4.90133851,  5.5418111 ,  1.47935199],
        [-5.54363908,  5.94633464,  1.89380072]])

El producto interno (producto escalar) entre dos arreglos que representan vectores se puede calcular usando la función <code>np.inner</code>:

In [ ]:
x = np.arange(1,10)
np.inner(x, x)

285


o, de manera equivalente, usando <code>np.dot</code>:

In [ ]:
np.dot(x, x)

285